"use client";

import { useEffect, useState, type FormEvent } from "react";
import MainLayout from "@/components/navigation/MainLayout";
import { crmApi, type IbOverview, type NetworkNode, type LedgerPage } from "@/lib/api";

export default function TraderIbPage() {
  const [overview, setOverview] = useState<IbOverview | null>(null); const [network, setNetwork] = useState<NetworkNode[]>([]); const [commissions, setCommissions] = useState<LedgerPage | null>(null); const [message, setMessage] = useState(""); const [amount, setAmount] = useState(""); const [destination, setDestination] = useState("");
  useEffect(() => { void Promise.all([crmApi.ibOverview(), crmApi.ibNetwork(), crmApi.ibCommissions()]).then(([nextOverview, nextNetwork, nextCommissions]) => { setOverview(nextOverview); setNetwork(nextNetwork); setCommissions(nextCommissions); }).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load IB portal.")); }, []);
  async function withdraw(event: FormEvent) { event.preventDefault(); try { await crmApi.ibWithdraw({ amount, destination }); setAmount(""); setDestination(""); setMessage("Withdrawal request submitted."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to request withdrawal."); } }
  const copy = () => { if (overview) void navigator.clipboard.writeText(overview.referral_link).then(() => setMessage("Referral link copied.")); };
  return <MainLayout><main className="mx-auto max-w-5xl"><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">Partner network</p><h1 className="mt-2 text-3xl font-semibold text-white">IB portal</h1><p className="mt-2 text-sm text-slate-500">Track referrals, commissions, and partner wallet activity.</p>{message && <p className="mt-4 rounded border border-slate-700 p-3 text-xs text-slate-300">{message}</p>}<section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Wallet balance" value={`$${Number(overview?.wallet_balance ?? 0).toFixed(2)}`} /><Metric label="Referred traders" value={String(overview?.referred_traders ?? 0)} /><Metric label="Earned commissions" value={`$${Number(overview?.total_earned_commissions ?? 0).toFixed(2)}`} /></section><section className="mt-5 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Referral link</h2><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input readOnly className="min-w-0 flex-1 rounded border border-slate-700 bg-[#070A11] p-3 text-xs text-slate-300" value={overview?.referral_link ?? "Loading..."} /><button className="rounded bg-cyan-400 px-4 py-3 text-xs font-bold text-slate-950" onClick={copy}>Copy link</button></div></section><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Downline network</h2><div className="mt-4 space-y-2">{network.map((node) => <Node node={node} key={node.id} />)}{network.length === 0 && <p className="text-sm text-slate-600">No referred traders yet.</p>}</div></section><section className="rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Request payout</h2><form onSubmit={(event) => void withdraw(event)} className="mt-4 space-y-3"><input required type="number" min="0.01" step="0.01" placeholder="Amount (USD)" className="w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" value={amount} onChange={(event) => setAmount(event.target.value)} /><input required placeholder="Bank account or wallet destination" className="w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" value={destination} onChange={(event) => setDestination(event.target.value)} /><button className="rounded bg-cyan-400 px-4 py-3 text-xs font-bold text-slate-950" type="submit">Submit withdrawal</button></form><div className="mt-6 space-y-2">{commissions?.items.map((entry) => <div className="flex justify-between border-b border-slate-800 py-2 text-xs" key={entry.id}><span className="text-slate-400">{entry.reference}</span><strong className="text-emerald-300">${entry.amount}</strong></div>)}</div></section></div></main></MainLayout>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="rounded-lg border border-slate-800 bg-[#0D121F] p-5"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><strong className="mt-2 block text-2xl text-white">{value}</strong></article>; }
function Node({ node }: { node: NetworkNode }) { return <div className="border-l border-cyan-500/30 pl-3 text-xs"><p className="text-slate-200">{node.full_name || node.email} <span className="ml-2 text-slate-600">Tier {node.level}</span></p>{node.children.map((child) => <Node key={child.id} node={child} />)}</div>; }
