"use client";

import { useEffect, useState } from "react";
import { crmApi, type MasterPaymentControl } from "@/lib/api";

export default function MasterPaymentsPage() {
  const [controls, setControls] = useState<MasterPaymentControl[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { void crmApi.masterPaymentControls().then(setControls).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load controls.")); }, []);
  async function save(control: MasterPaymentControl) { try { await crmApi.saveMasterPaymentControl(control); setMessage(`${control.asset} ${control.network} control saved.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save control."); } }
  return <main className="min-h-screen bg-[#070A11] px-4 py-8 text-slate-100 sm:px-8"><div className="mx-auto max-w-4xl"><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">SaaS master controls</p><h1 className="mt-2 text-3xl font-semibold text-white">Payment availability</h1><p className="mt-2 text-sm text-slate-500">A disabled global control overrides every broker configuration.</p>{message && <p className="mt-4 rounded border border-slate-700 p-3 text-xs text-slate-300">{message}</p>}<div className="mt-6 space-y-3">{controls.map((control) => <div className="flex items-center justify-between rounded-lg border border-slate-800 bg-[#0D121F] p-4" key={control.id}><span className="text-sm text-white">{control.asset} · {control.network} <small className="ml-2 text-slate-600">{control.tenant_id ? `Tenant ${control.tenant_id}` : "Global"}</small></span><button className={control.is_active_master ? "rounded bg-emerald-400 px-3 py-2 text-xs font-bold text-slate-950" : "rounded bg-rose-400 px-3 py-2 text-xs font-bold text-slate-950"} onClick={() => { const next = { ...control, is_active_master: !control.is_active_master }; setControls((current) => current.map((item) => item.id === control.id ? next : item)); void save(next); }}>{control.is_active_master ? "Enabled" : "Disabled"}</button></div>)}</div></div></main>;
}