"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { UserRound } from "lucide-react";

export default function TraderRegisterPage() {
  const [form, setForm] = useState({ name: "", email: "", password: "", phone: "", country: "", platform: "MT5", account_type: "Live", terms: false });
  const router = useRouter();
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.terms) { setError("Please accept the Terms & Conditions."); return; } setLoading(true); setError(""); const hostname = window.location.hostname; const ref = new URLSearchParams(window.location.search).get("ref"); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/api/v1/auth/register${ref ? `?ref=${encodeURIComponent(ref)}` : ""}`, { method: "POST", headers: { "Content-Type": "application/json", "X-Tenant-Host": hostname }, body: JSON.stringify({ email: form.email, password: form.password, full_name: form.name, phone: form.phone, country: form.country }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail ?? "Registration failed."); router.push("/trader/login"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Registration failed."); } finally { setLoading(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#070A11] p-5 text-slate-200"><section className="w-full max-w-xl rounded-lg border border-slate-800 bg-[#0D121F] p-7"><div className="mb-6"><UserRound className="mb-3 text-cyan-300" size={22} /><p className="text-[10px] uppercase tracking-widest text-cyan-400">{typeof window === "undefined" ? "Broker workspace" : window.location.hostname}</p><h1 className="mt-2 text-2xl font-semibold text-white">Create trader account</h1></div><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}>{[["name", "Full name"], ["email", "Email"], ["password", "Password"], ["phone", "Phone"]].map(([key, label]) => <label className="text-xs text-slate-400" key={key}>{label}<input className="auth-input" required value={form[key as keyof typeof form] as string} type={key === "password" ? "password" : key === "email" ? "email" : "text"} onChange={(event) => update(key, event.target.value)} /></label>)}<label className="text-xs text-slate-400">Country<select className="auth-input" required value={form.country} onChange={(event) => update("country", event.target.value)}><option value="">Select country</option><option>Pakistan</option><option>United Kingdom</option><option>United Arab Emirates</option><option>United States</option></select></label><label className="text-xs text-slate-400">Platform<select className="auth-input" value={form.platform} onChange={(event) => update("platform", event.target.value)}><option>MT5</option><option>MT4</option></select></label><label className="text-xs text-slate-400">Account type<select className="auth-input" value={form.account_type} onChange={(event) => update("account_type", event.target.value)}><option>Live</option><option>Demo</option></select></label><label className="flex items-center gap-2 self-end text-xs text-slate-400"><input type="checkbox" checked={form.terms} onChange={(event) => update("terms", event.target.checked)} /> I accept the <a className="text-cyan-300" href="/terms">Terms & Conditions</a>.</label>{error && <p className="text-xs text-rose-300 sm:col-span-2">{error}</p>}<button className="auth-button sm:col-span-2" disabled={loading} type="submit">{loading ? "Creating account..." : "Create account"}</button></form></section></main>;
}
