"use client";

import { useEffect, useState } from "react";
import { crmApi, type PaymentMethod } from "@/lib/api";

const catalog: PaymentMethod[] = [
  ["CRYPTO", "TRC20", "USDT"], ["CRYPTO", "BEP20", "USDT"], ["CRYPTO", "BEP20", "USDC"], ["CRYPTO", "ERC20", "USDT"], ["CRYPTO", "ERC20", "USDC"], ["CRYPTO", "ERC20", "ETH"], ["CRYPTO", "POLYGON", "USDT"], ["CRYPTO", "POLYGON", "USDC"], ["CRYPTO", "POLYGON", "MATIC"], ["CRYPTO", "SOLANA", "USDT"], ["CRYPTO", "SOLANA", "SOL"], ["CRYPTO", "BTC_NATIVE", "BTC"], ["BANK_WIRE", "SWIFT", "FIAT"], ["BANK_LOCAL", "LOCAL", "FIAT"], ["E_WALLET", "SKRILL", "FIAT"], ["E_WALLET", "NETELLER", "FIAT"], ["E_WALLET", "PERFECT_MONEY", "FIAT"], ["E_WALLET", "EPAY", "FIAT"], ["E_WALLET", "PAYEER", "FIAT"], ["CUSTOM", "CUSTOM", "FIAT"],
].map(([method, network, asset]) => ({ method, network, asset, min_deposit: 0, min_withdrawal: 0, processing_fee: 0, is_active_broker: false }));

export default function PaymentSettingsPage() {
  const [methods, setMethods] = useState<PaymentMethod[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { void crmApi.brokerPaymentMethods().then((current) => setMethods(catalog.map((item) => current.find((saved) => saved.method === item.method && saved.network === item.network && saved.asset === item.asset) ?? item))).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load payment methods.")); }, []);
  function update(index: number, patch: Partial<PaymentMethod>) { setMethods((current) => current.map((method, itemIndex) => itemIndex === index ? { ...method, ...patch } : method)); }
  async function save(method: PaymentMethod) { try { await crmApi.saveBrokerPaymentMethod(method); setMessage(`${method.asset} ${method.network} saved.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save payment method."); } }
  return <main className="min-h-screen bg-[#070A11] px-4 py-8 text-slate-100 sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-5 flex items-center justify-between gap-3"><button className="back-button" type="button" onClick={() => window.history.back()}><span className="button-arrow" aria-hidden="true">←</span> Back</button></div><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">Broker administration</p><h1 className="mt-2 text-3xl font-semibold text-white">Payment methods</h1><p className="mt-2 text-sm text-slate-500">Configure only the networks approved by the SaaS master controls.</p>{message && <p className="mt-4 rounded border border-slate-700 p-3 text-xs text-slate-300">{message}</p>}<div className="mt-6 space-y-3">{methods.map((method, index) => <section className="rounded-lg border border-slate-800 bg-[#0D121F] p-4" key={`${method.method}-${method.network}-${method.asset}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm text-white">{method.asset} · {method.network}</strong><p className="mt-1 text-xs text-slate-500">{method.method}</p></div><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={method.is_active_broker} onChange={(event) => update(index, { is_active_broker: event.target.checked })} /> Enabled</label></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Field label="Deposit address / account" value={method.deposit_address ?? ""} onChange={(value) => update(index, { deposit_address: value })} /><Field label="QR code URL" value={method.qr_code_url ?? ""} onChange={(value) => update(index, { qr_code_url: value })} /><Field label="Minimum deposit" value={String(method.min_deposit)} onChange={(value) => update(index, { min_deposit: value })} /><Field label="Processing fee" value={String(method.processing_fee)} onChange={(value) => update(index, { processing_fee: value })} /></div><button className="mt-4 rounded bg-cyan-400 px-4 py-2 text-xs font-bold text-slate-950" onClick={() => void save(method)}>Save method</button></section>)}</div></div></main>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs text-slate-400">{label}<input className="mt-2 w-full rounded border border-slate-700 bg-[#070A11] p-2.5 text-sm text-white" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }