"use client";

import { useEffect, useState, type DragEvent, type FormEvent } from "react";
import MainLayout from "@/components/navigation/MainLayout";
import { crmApi, type KycDocument } from "@/lib/api";
import { useToast } from "@/components/ui/ToastProvider";

const accepted = ["image/jpeg", "image/png", "application/pdf"];

export default function TraderKycPage() {
  const [documents, setDocuments] = useState<KycDocument[]>([]);
  const [type, setType] = useState("PASSPORT");
  const [file, setFile] = useState<File | null>(null);
  const [dragging, setDragging] = useState(false);
  const showToast = useToast();
  useEffect(() => { void crmApi.kycDocuments().then(setDocuments).catch((error) => showToast(error instanceof Error ? error.message : "Unable to load KYC.", "error")); }, [showToast]);
  function selectFile(candidate: File | undefined) { if (!candidate) return; if (!accepted.includes(candidate.type) || candidate.size > 10 * 1024 * 1024) { showToast("Use a PDF, JPG, or PNG smaller than 10 MB.", "error"); return; } setFile(candidate); }
  function drop(event: DragEvent<HTMLLabelElement>) { event.preventDefault(); setDragging(false); selectFile(event.dataTransfer.files[0]); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) { showToast("Choose a document first.", "error"); return; } try { const upload = await crmApi.kycUploadUrl({ document_type: type, content_type: file.type }); const uploaded = await fetch(upload.upload_url, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!uploaded.ok) throw new Error("Document upload failed."); await crmApi.submitKyc({ document_type: type, storage_key: upload.storage_key, fields: {} }); setFile(null); setDocuments(await crmApi.kycDocuments()); showToast("KYC document submitted for review."); } catch (error) { showToast(error instanceof Error ? error.message : "Unable to submit KYC.", "error"); } }
  return <MainLayout><main className="mx-auto max-w-3xl"><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">Verification</p><h1 className="mt-2 text-3xl font-semibold text-white">Identity verification</h1><p className="mt-2 text-sm text-slate-500">Submit identity documents securely for compliance review.</p><form onSubmit={(event) => void submit(event)} className="mt-6 space-y-4 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><label className="block text-xs text-slate-400">Document type<select className="mt-2 w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" value={type} onChange={(event) => setType(event.target.value)}><option>PASSPORT</option><option>ID_CARD</option><option>PROOF_OF_ADDRESS</option></select></label><label onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop} className={`block cursor-pointer rounded-lg border-2 border-dashed p-8 text-center transition ${dragging ? "scale-[1.01] border-blue-500 bg-blue-500/10" : "border-slate-700 bg-[#070A11] hover:border-cyan-400/60"}`}><span className="block text-sm text-slate-300">{file ? file.name : "Drop your document here or browse"}</span><small className="mt-2 block text-xs text-slate-600">PDF, JPG, or PNG up to 10 MB</small><input required={!file} accept="image/jpeg,image/png,application/pdf" className="sr-only" type="file" onChange={(event) => selectFile(event.target.files?.[0])} /></label><button className="rounded bg-cyan-400 px-4 py-3 text-xs font-bold text-slate-950" type="submit">Upload and submit</button></form><section className="mt-5 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Submission history</h2><div className="relative mt-4"><div className="overflow-x-auto"><table className="w-full min-w-120 text-left text-xs"><thead className="border-b border-slate-800 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-3">Document</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Submitted</th></tr></thead><tbody className="divide-y divide-slate-800/70">{documents.map((document) => <tr key={document.id}><td className="px-3 py-3 text-slate-300">{document.document_type}</td><td className="px-3 py-3"><span className="rounded bg-slate-800 px-2 py-1 text-slate-400">{document.status}</span></td><td className="px-3 py-3 text-slate-500">{new Date(document.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div><div className="pointer-events-none absolute inset-y-0 right-0 w-10 bg-linear-to-l from-slate-900/90 to-transparent" /></div>{documents.length === 0 && <p className="mt-4 text-sm text-slate-600">No documents submitted.</p>}</section></main></MainLayout>;
}
