"use client";

import { useEffect, useState, type FormEvent } from "react";
import MainLayout from "@/components/navigation/MainLayout";
import { crmApi, type KycDocument } from "@/lib/api";

export default function TraderKycPage() {
  const [documents, setDocuments] = useState<KycDocument[]>([]); const [type, setType] = useState("PASSPORT"); const [message, setMessage] = useState(""); const [file, setFile] = useState<File | null>(null);
  useEffect(() => { void crmApi.kycDocuments().then(setDocuments).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load KYC.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { if (!file) throw new Error("Choose a document first."); const upload = await crmApi.kycUploadUrl({ document_type: type, content_type: file.type }); const uploaded = await fetch(upload.upload_url, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!uploaded.ok) throw new Error("Document upload failed."); await crmApi.submitKyc({ document_type: type, storage_key: upload.storage_key, fields: {} }); setFile(null); setDocuments(await crmApi.kycDocuments()); setMessage("KYC document submitted for review."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit KYC."); } }
  return <MainLayout><main className="mx-auto max-w-3xl"><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">Verification</p><h1 className="mt-2 text-3xl font-semibold text-white">Identity verification</h1><p className="mt-2 text-sm text-slate-500">Submit your identity documents securely for compliance review.</p>{message && <p className="mt-4 rounded border border-slate-700 p-3 text-xs text-slate-300">{message}</p>}<form onSubmit={(event) => void submit(event)} className="mt-6 space-y-4 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><label className="block text-xs text-slate-400">Document type<select className="mt-2 w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" value={type} onChange={(event) => setType(event.target.value)}><option>PASSPORT</option><option>ID_CARD</option><option>PROOF_OF_ADDRESS</option></select></label><label className="block text-xs text-slate-400">Document file<input required accept="image/jpeg,image/png,application/pdf" className="mt-2 w-full text-sm text-slate-300" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button className="rounded bg-cyan-400 px-4 py-3 text-xs font-bold text-slate-950" type="submit">Upload and submit</button></form><section className="mt-5 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Submission history</h2><div className="mt-4 space-y-3">{documents.map((document) => <div className="flex items-center justify-between border-b border-slate-800 py-3 text-xs" key={document.id}><span className="text-slate-300">{document.document_type}</span><span className="rounded bg-slate-800 px-2 py-1 text-slate-400">{document.status}</span></div>)}{documents.length === 0 && <p className="text-sm text-slate-600">No documents submitted.</p>}</div></section></main></MainLayout>;
}
