"use client";

import { useEffect, useState, type FormEvent } from "react";
import MainLayout from "@/components/navigation/MainLayout";
import { crmApi, type Profile } from "@/lib/api";

export default function TraderProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [message, setMessage] = useState(""); const [secret, setSecret] = useState(""); const [code, setCode] = useState("");
  useEffect(() => { void crmApi.profile().then(setProfile).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load profile.")); }, []);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; try { setProfile(await crmApi.updateProfile({ full_name: profile.full_name, phone: profile.phone, country: profile.country, address: profile.address })); setMessage("Profile updated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update profile."); } }
  async function start2fa() { try { const result = await crmApi.setup2fa(); setSecret(result.secret); setMessage("Scan the provisioning URI, then enter the six-digit code."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to start 2FA."); } }
  async function verify2fa(event: FormEvent) { event.preventDefault(); try { await crmApi.verify2fa(code); setProfile((current) => current ? { ...current, totp_enabled: true } : current); setSecret(""); setCode(""); setMessage("Two-factor authentication enabled."); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid verification code."); } }
  return <MainLayout><main className="mx-auto max-w-3xl"><p className="text-[10px] uppercase tracking-[.2em] text-cyan-400">Account security</p><h1 className="mt-2 text-3xl font-semibold text-white">Trader profile</h1><p className="mt-2 text-sm text-slate-500">Manage identity details and account security.</p>{message && <p className="mt-4 rounded border border-slate-700 p-3 text-xs text-slate-300">{message}</p>}<form onSubmit={(event) => void save(event)} className="mt-6 grid gap-4 rounded-lg border border-slate-800 bg-[#0D121F] p-6 sm:grid-cols-2">{(["full_name", "phone", "country", "address"] as const).map((key) => <label className="text-xs text-slate-400" key={key}>{key.replace("_", " ")}<input className="mt-2 w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" value={profile?.[key] ?? ""} onChange={(event) => setProfile((current) => current ? { ...current, [key]: event.target.value } : current)} maxLength={key === "country" ? 2 : undefined} /></label>)}<button className="rounded bg-cyan-400 px-4 py-3 text-xs font-bold text-slate-950 sm:col-span-2" disabled={!profile} type="submit">Save profile</button></form><section className="mt-5 rounded-lg border border-slate-800 bg-[#0D121F] p-6"><h2 className="font-semibold text-white">Two-factor authentication</h2><p className="mt-2 text-sm text-slate-500">Status: {profile?.totp_enabled ? "Enabled" : "Not enabled"}</p>{!profile?.totp_enabled && <button className="mt-4 rounded border border-cyan-400/50 px-3 py-2 text-xs text-cyan-300" onClick={() => void start2fa()}>Set up 2FA</button>}{secret && <form className="mt-4 space-y-3" onSubmit={(event) => void verify2fa(event)}><p className="break-all rounded bg-[#070A11] p-3 font-mono text-xs text-slate-300">Secret: {secret}</p><input required pattern="[0-9]{6}" inputMode="numeric" className="w-full rounded border border-slate-700 bg-[#070A11] p-3 text-sm text-white" placeholder="123456" value={code} onChange={(event) => setCode(event.target.value)} /><button className="rounded bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950" type="submit">Verify code</button></form>}</section></main></MainLayout>;
}
